import CalculateIcon from "@mui/icons-material/Calculate";
import TerminalIcon from "@mui/icons-material/Terminal";

export const courses = [
  {
    id: "SWE 353",
    title: "Web Engineering",
    icon: <CalculateIcon />,
    description: "Covers client/server web development, frameworks, and engineering principles.",
    department: "SWE",
  },
  {
    id: "ICS 104",
    title: "Python",
    icon: <TerminalIcon />,
    description: "Introduction to programming using Python with a focus on problem-solving.",
    department: "ICS",
  },
  {
    id: "ICS 500",
    title: "Methodology",
    icon: <TerminalIcon />,
    description: "Graduate-level study of software engineering methodologies and processes.",
    department: "ICS",
  },
  {
    id: "MATH 001",
    title: "Pre-Calculus",
    icon: <CalculateIcon />,
    description: "Foundational math concepts preparing students for calculus.",
    department: "MATH",
  },
  {
    id: "MATH 002",
    title: "Calculus 1",
    icon: <CalculateIcon />,
    description: "Differential calculus with applications to science and engineering.",
    department: "MATH",
  },
  {
    id: "MATH 101",
    title: "Calculus 2",
    icon: <CalculateIcon />,
    description: "Integral calculus and advanced applications building on Calculus 1.",
    department: "MATH",
  },
  {
    id: "MATH 102",
    title: "Differential Equations",
    icon: <CalculateIcon />,
    description: "Solving ordinary differential equations used in engineering and physics.",
    department: "MATH",
  },
  {
    id: "MATH 108",
    title: "Statistics",
    icon: <CalculateIcon />,
    description: "Introduction to statistics, probability, and data analysis techniques.",
    department: "MATH",
  },
  {
    id: "MATH 201",
    title: "Calculus 3",
    icon: <CalculateIcon />,
    description: "Multivariable calculus including vectors, partial derivatives, and triple integrals.",
    department: "MATH",
  },
  {
    id: "MATH 208",
    title: "Linear Algebra",
    icon: <CalculateIcon />,
    description: "Matrices, vectors, linear systems, and fundamental algebraic structures.",
    department: "MATH",
  },
  {
    id: "COE 292",
    title: "Digital Logic Design",
    icon: <TerminalIcon />,
    description: "Introduction to digital circuits, logic gates, and hardware design concepts.",
    department: "COE",
  },
  {
    id: "IAS 430",
    title: "Ethics & Society",
    icon: <CalculateIcon />,
    description: "Examines social and ethical issues in technology and modern society.",
    department: "IAS",
  },
  {
    id: "COE 233",
    title: "Computer Organization",
    icon: <TerminalIcon />,
    description: "Covers computer architecture, memory, processors, and low-level operations.",
    department: "COE",
  },
  {
    id: "SWE 216",
    title: "Software Requirements",
    icon: <CalculateIcon />,
    description: "Introduction to requirements engineering, analysis, documentation, and modeling.",
    department: "SWE",
  },
  {
    id: "ICS 253",
    title: "Discrete Structures",
    icon: <TerminalIcon />,
    description: "Mathematical foundations of computer science including logic, sets, and graphs.",
    department: "ICS",
  },
];
